export const mockAccounts = [
  {
    id: 'acc_bca_tahapan_1',
    name: 'BCA Tahapan Gold',
    institutionSlug: 'bca',
    type: 'bank',
    balance: 85200501,
    accountNumber: '2847',
    isPinned: true,
  },
  {
    id: 'acc_bca_kredit_2',
    name: 'BCA Everyday Card',
    institutionSlug: 'bca',
    type: 'loan', 
    balance: 4500000,
    accountNumber: '5588',
  },
  {
    id: 'acc_gopay_main_3',
    name: 'GoPay',
    institutionSlug: 'gopay',
    type: 'e-wallet',
    balance: 1068000,
    accountNumber: '7890',
  },
  {
    id: 'acc_mandiri_payroll_4',
    name: 'Mandiri Payroll',
    institutionSlug: 'mandiri',
    type: 'bank',
    balance: 42500000,
    accountNumber: '5566',
  },
  {
    id: 'acc_bibit_main_5',
    name: 'Bibit Portfolio',
    institutionSlug: 'bibit',
    type: 'investment',
    balance: 125000000,
    accountNumber: 'IVST',
  },
  {
    id: 'acc_pintu_main_6',
    name: 'Pintu Crypto',
    institutionSlug: 'pintu',
    type: 'investment',
    balance: 75000000,
    accountNumber: 'CRPT',
  },
  {
    id: 'acc_kredivo_loan_7',
    name: 'Kredivo PayLater',
    institutionSlug: 'kredivo',
    type: 'loan',
    balance: 5500000,
    accountNumber: 'LOAN',
  },
];

export const mockTransactions = [
  { id: 'txn_1', accountId: 'acc_bca_tahapan_1', amount: 55000000, date: '2024-07-25', description: 'Salary Deposit', category: 'Income' },
  { id: 'txn_2', accountId: 'acc_bca_tahapan_1', amount: -1800000, date: '2024-07-24', description: 'Dinner at SKYE', category: 'Food and Drink' },
  { id: 'txn_3', accountId: 'acc_bca_tahapan_1', amount: -3200000, date: '2024-07-19', description: 'Garuda Flight to Bali', category: 'Travel' },
  { id: 'txn_4', accountId: 'acc_gopay_main_3', amount: -120000, date: '2024-07-26', description: "GoFood McDonald's", category: 'Food and Drink' },
  { id: 'txn_5', accountId: 'acc_gopay_main_3', amount: -35000, date: '2024-07-23', description: 'Gojek Ride', category: 'Transportation' },
  { id: 'txn_6', accountId: 'acc_bca_kredit_2', amount: -2500000, date: '2024-07-27', description: 'Shopping at Zara', category: 'Shopping' },
  { id: 'txn_7', accountId: 'acc_bca_kredit_2', amount: -54999, date: '2024-07-27', description: 'Spotify Premium', category: 'Services' },
  { id: 'txn_8', accountId: 'acc_mandiri_payroll_4', amount: 45000000, date: '2024-06-30', description: 'Bonus Tahunan', category: 'Income' },
  { id: 'txn_9', accountId: 'acc_mandiri_payroll_4', amount: -250000, date: '2024-07-31', description: 'Biaya Admin', category: 'Fees'},
  { id: 'txn_10', accountId: 'acc_kredivo_loan_7', amount: -5500000, date: '2024-07-01', description: 'Pembayaran Tagihan Kredivo', category: 'Payments' },
];
